Visit_Manager/Controllers/VisitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Net;
using System.Net.Mail;
using System.Globalization;
using System.IO;
using System.IO.Packaging;
using iTextSharp;
using iTextSharp.text;
using iTextSharp.text.pdf;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Spreadsheet;
using DocumentFormat.OpenXml.Packaging;
using Visit_Manager.Models;
using Visit_Manager.Repository;


namespace Visit_Manager.Controllers
{
    public class VisitController : BaseController
    {

        // GET: Visit

        #region Methods in Index view

        public ActionResult Index()
        {
            if (Is_user_logged_in())
            {
                Visit_typeRepository visit_type_repo = new Visit_typeRepository();
                EmployeeRepository employee_repo = new EmployeeRepository();
                List<Employee> list_of_employees = new List<Employee>();
                List<Visit_type> list_of_visit_types = new List<Visit_type>();
                Visit_model model = new Visit_model();

                model.List_of_employees_to_ddl = new List<SelectListItem>();
                model.List_of_visit_types_to_ddl = new List<SelectListItem>();

                try
                {
                    list_of_employees = employee_repo.Get_all_except_admin();
                    list_of_visit_types = visit_type_repo.Get_all_not_removed();

                    foreach (var user in list_of_employees)
                    {
                        model.List_of_employees_to_ddl.Add(new SelectListItem
                        {
                            Text = user.name + " " + user.surname,
                            Value = user.id.ToString()
                        });
                    }
                    foreach (var type in list_of_visit_types)
                    {
                        model.List_of_visit_types_to_ddl.Add(new SelectListItem
                        {
                            Text = type.name,
                            Value = type.id.ToString()
                        });
                    }
                }
                catch (Exception ex)
                {
                    NLog_logger.Loger.Error(ex);
                }

                return View(model);
            }
            else
            {
                return RedirectToAction("Login", "Employee");
            }
        }

        [HttpGet]
        public ActionResult Get_visits_from_db(string date)
        {
            Visit_model model = new Visit_model();

            if (Is_user_logged_in())
            {
                try
                {
                    DateTime visit_date = Convert_string_to_datetime(date);
                    model.List_of_visits_to_view = Return_visits(visit_date);
                    model.If_session_expired = false;
                }
                catch (Exception ex)
                {
                    NLog_logger.Loger.Error(ex);
                }

                // Sorting must be in return
                return Json(model.List_of_visits_to_view
                         .OrderBy(a => a.Employee_id)
                         .ThenBy(a => a.Start_time.TimeOfDay)
                         .ToList(),
                         JsonRequestBehavior.AllowGet);
            }
            else
            {
                model.If_session_expired = true;
                return Json(model, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult Get_visit_to_edit(long id)
        {
            Is_user_logged_in(); // Checks whether the session has not expired yet and possibly updates it

            VisitRepository visit_repo = new VisitRepository();
            Visit_typeRepository visit_type_repo = new Visit_typeRepository();
            EmployeeRepository employee_repo = new EmployeeRepository();
            Visit visit_from_db = new Visit();
            Visit_in_view visit_to_edit = new Visit_in_view();
            bool if_employee_removed = false;
            bool if_visit_type_removed = false;

            try
            {
                visit_from_db = visit_repo.Get_by_id(id);
                if_employee_removed = employee_repo.Check_if_removed(visit_from_db.employee_id);
                if_visit_type_removed = visit_type_repo.Check_if_removed(visit_from_db.type_id);// db.Visit_type.Find(visit_from_db.type_id).is_removed;

                if (visit_from_db != null)
                {
                    visit_to_edit = new Visit_in_view()
                    {
                        Id = visit_from_db.id,
                        Client_name = visit_from_db.client_name,
                        Client_surname = visit_from_db.client_surname,
                        Client_email = visit_from_db.client_email,
                        Client_tel_number = visit_from_db.client_tel_number,
                        Describe = visit_from_db.describe,
                        Employee_id = visit_from_db.employee_id,
                        Start_time = visit_from_db.start_time,
                        End_time = visit_from_db.end_time,
                        Price = visit_from_db.price,
                        Type_id = visit_from_db.type_id,
                        Type_unclassified = visit_from_db.type_unclassified
                    };

                    if (if_employee_removed)
                    {
                        // This if is needed to edit visit when the doctor to whom the visit
                        // was previously arranged has been removed, in modal-edit_visit_
                        // when choosing the default value visit was placeholder = 'select doctor' and not empty field as null

                        visit_to_edit.Employee_id = 0;
                    }
                    if (if_visit_type_removed)
                    {
                        visit_to_edit.Type_id = 0;
                    }
                }
            }
            catch (Exception ex)
            {
                NLog_logger.Loger.Error(ex);
            }

            return Json(visit_to_edit, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Add_new_visit(Visit_from_view new_visit)
        {
            Visit_model model = new Visit_model();

            if (Is_user_logged_in())
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                        VisitRepository visit_repo = new VisitRepository();
                        EmployeeRepository employee_repo = new EmployeeRepository();
                        List<Visit> list_of_visits = new List<Visit>();
                        List<Employee> list_of_employees = new List<Employee>();
                        bool if_email_sent = false;

                        model.List_of_results = new List<Return_result>();
                        model.If_action_successed = true;
                        model.If_session_expired = false;

                        DateTime date = Convert_string_to_datetime(new_visit.Visit_date);

                        DateTime start_time_visit = new DateTime(date.Year, date.Month, date.Day, new_visit.Start_time.Hours, new_visit.Start_time.Minutes, new_visit.Start_time.Seconds);
                        DateTime end_time_visit = new DateTime(date.Year, date.Month, date.Day, new_visit.End_time.Hours, new_visit.End_time.Minutes, new_visit.End_time.Seconds);


                        list_of_visits = visit_repo.Get_list_by_date_and_employee_id(start_time_visit, new_visit.Employee_id);

                        if (list_of_visits.Count > 0)
                        {
                            // Checking if the added visit does not interfere with other visits on an hourly basis
                            model.List_of_results = Validate_time_of_visit(start_time_visit, end_time_visit, list_of_visits);
                        }
                        if (model.List_of_results.Count == 0)
                        {
                            // Converting data to the Visit class so that this object can be added to the database
                            Visit visit_to_db = new Visit();
                            visit_to_db.client_name = new_visit.Client_name;
                            visit_to_db.client_surname = new_visit.Client_surname;
                            visit_to_db.client_tel_number = new_visit.Client_tel_number;
                            visit_to_db.client_email = new_visit.Client_email;
                            visit_to_db.employee_id = new_visit.Employee_id;
                            visit_to_db.start_time = start_time_visit;
                            visit_to_db.end_time = end_time_visit;
                            visit_to_db.describe = new_visit.Describe;
                            visit_to_db.is_removed = false;
                            visit_to_db.price = new_visit.Price;
                            visit_to_db.type_id = new_visit.Type_id;
                            if (visit_to_db.type_id == 1)
                            {
                                visit_to_db.type_unclassified = new_visit.Type_unclassified;
                            }

                            visit_repo.Add(visit_to_db);


                            if (model.If_action_successed)
                            {
                                model.List_of_results.Add(new Return_result
                                {
                                    Result = true,
                                    Content = Resources.Global.Result_visit_added_correct

                                });

                                list_of_employees = employee_repo.Get_all_except_admin();
                                // Sending an email
                                Visit_mail visit = new Visit_mail()
                                {

Visit_Manager/Views/Visit/Admin.cshtml
@model Visit_Manager.Models.Visit_model
@{
    ViewBag.Title = Resources.Global.Admin_panel;
}
<head>
    <title>@ViewBag.Title - @Html.Raw(Resources.Global.Visit_manager) </title>
    <link type="text/css" rel="stylesheet" href="~/Content/view_admin.css" />@*Custom style*@

    <script type="text/javascript" src="~/Scripts/view_admin.js"></script>@*Custom script*@
</head>

@Html.Partial("_Admin_modal_windows")

<!-- #region Navigation bar -->
<nav aria-label="...">
    <ul class="pager">
        <li>
            <a href="#" data-target="#modal_add_employee" data-toggle="modal">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                @Html.Raw(Resources.Global.New_employee)
            </a>
        </li>
        <li>
            <a href="#" data-target="#modal_edit_employee" data-toggle="modal" onclick="Get_users_to_ddl();">
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                @Html.Raw(Resources.Global.Edit_remove_employee)
            </a>
        </li>
        <li>
            <a href="#" data-target="#modal_add_visit_type" data-toggle="modal">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                @Html.Raw(Resources.Global.New_visit_type)
            </a>
        </li>
        <li>
            <a href="#" data-target="#modal_edit_visit_type" data-toggle="modal" onclick="Get_visit_type_to_ddl();">
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                @Html.Raw(Resources.Global.Edit_remove_visit_type)
            </a>
        </li>
        <li>
            <a href="#" data-target="#modal_change_password" data-toggle="modal">
                <i class="fa fa-cog" aria-hidden="true"></i>
                @Html.Raw(Resources.Global.Change_password)
            </a>
        </li>
    </ul>
</nav>
<!-- #endregion -->
<!-- #region Top chart -->
<div class="container">
    <div class=" row">
        <div class="col-md-12" id="top_chart">

            @*============top chart============*@

        </div>
    </div>
</div>
<hr />
<!-- #endregion -->
<!-- #region Date picker -->
<div class="container" id="div_dp_range">
    <div class="row">
        <div class=" col-md-4">
            <div class='input-group'>
                <span class="input-group-addon"><span class="glyphicon glyphicon-calendar "></span></span>
                <input class="form-control"
                       id="dp_range"
                       type="text"
                       name="daterange"
                       readonly="readonly"
                       onchange="Get_data_to_bottom_charts();" />

            </div>
        </div>
        <div class=" col-md-8">
            <h4>@Html.Raw(Resources.Global.Select_data_range)<span style="color:red;">&nbsp;@Html.Raw(Resources.Global.Completed)&nbsp;</span>@Html.Raw(Resources.Global._visits)</h4>
        </div>
    </div>
</div>

<!-- #endregion -->
<!-- #region Bottom charts -->
<div id="bottom_charts_div">
    <div class="container" id="bottom_charts">

        @*============top chart============*@

    </div>
    <br />
</div>
<!-- #endregion -->

Visit_Manager/Views/Visit/Index.cshtml
@model Visit_Manager.Models.Visit_model
@{
    ViewBag.Title = Resources.Global.Visits;
}
<head>
    <title>@ViewBag.Title - @Html.Raw(Resources.Global.Visit_manager) </title>
    <link type="text/css" rel="stylesheet" href="~/Content/view_index.css" />@*Custom style*@

    <script type="text/javascript" src="~/Scripts/view_index.js"></script>@*Custom script*@
</head>

@Html.Partial("_Index_modal_windows")

<!-- #region Top of body-->
<div class="container" id="top">
    <div class="row">
        <div class="hidden-xs col-sm-3">
            <img src="~/Images/favicon.ico" class=" margin_top" height="80" width="80" />
        </div>


        <div class="col-xs-2 col-sm-1 text-center padding_0">
            <button class="btn btn_change_date " id="btn_date_backwards" onclick="Subtract_day()" type="button">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </button>
        </div>

        <div class="col-xs-8 col-sm-3 text-center ">

            <label class="sr-only" id="label_top_datepicker ">top_datepicker</label>

            <div class='input-group' id="div_top_datepicker">
                <span class="input-group-addon"><span class="glyphicon glyphicon-calendar "></span></span>
                <input class="form-control"
                       id="top_datepicker"
                       name="top_datepicker"
                       type="text"
                       readonly="readonly"
                       placeholder="Data wizyty" />
            </div>
        </div>

        <div class="col-xs-2 col-sm-1 text-center padding_0 ">
            <button class="btn btn_change_date " id="btn_date_forward" onclick="Add_day()" type="button">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </button>
        </div>

        <div class="col-xs-6 col-sm-2">
            <nav aria-label="...">
                <ul class="pager">

                    @using (Html.BeginForm("Download_visits_in_xlsx", "Visit", FormMethod.Get, new { id = "form_download_excel" }))
                    {
                        @Html.HiddenFor(a => a.Visit_date, new
                                {
                                    @class = "hidden_visit_date",
                                });

                        <li><a href="javascript:$('#form_download_excel').submit();"><span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>@Html.Raw(Resources.Global.Download_excel)</a></li>
                    }

                    @using (Html.BeginForm("Download_visits_in_pdf", "Visit", FormMethod.Get, new { id = "form_download_pdf" }))
                    {
                        @Html.HiddenFor(a => a.Visit_date, new
                                {
                                    @class = "hidden_visit_date",
                                });

                        <li><a href="javascript:$('#form_download_pdf').submit();"><span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>@Html.Raw(Resources.Global.Download_pdf)</a></li>
                    }
                </ul>
            </nav>

        </div>

        <div class="col-xs-6 col-sm-2">

            <button class="btn btn-success" id="btn_new_visit" data-target="#modal_add_visit" data-toggle="modal" type="button">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                @Html.Raw(Resources.Global.New_visit)
            </button>
        </div>
    </div>
</div>
<!--#endregion-->
<!--#region Displaing visits-->
<div class="container" id="div_table_visit">

</div>
<div class="container" id="div_table_mobile_visit">

</div>

<div class="container">
    <h2 id="is_clients"></h2>
</div>
<!--#endregion-->